/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Dominio.AJugador;
import Dominio.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author cristian
 */
public class Juego extends javax.swing.JFrame {

    AJugador jugador;

    /**
     * Creates new form Login
     */
    public Juego() {
        initComponents();
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        cmbOpciones.setVisible(false);
        labelLogin.setVisible(false);
        cmbOpciones.setEnabled(false);
        labelLogin.setEnabled(false);
        System.out.println("El ancho es: " + panelLogin.getWidth());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        txtNick = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        cmbLogin = new javax.swing.JComboBox<>();
        cmbOpciones = new javax.swing.JComboBox<>();
        labelLogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelPreguntas = new javax.swing.JPanel();
        labelPreguntas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnPreguntas = new javax.swing.JButton();
        panelJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nickname:");

        jLabel2.setText("Password:");

        cmbLogin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Seleccione>>", "1-Registrar", "2-Iniciar Sesión" }));
        cmbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLoginActionPerformed(evt);
            }
        });

        cmbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Opciones>>", "1-Preguntas", "2-Juego" }));
        cmbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpcionesActionPerformed(evt);
            }
        });

        labelLogin.setText("¿Què desea hacer?");

        jButton1.setText("Instrucciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNick)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLogin)
                            .addComponent(cmbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(cmbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Login", panelLogin);

        labelPreguntas.setText("jLabel3");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnPreguntas.setText("Registrar");

        javax.swing.GroupLayout panelPreguntasLayout = new javax.swing.GroupLayout(panelPreguntas);
        panelPreguntas.setLayout(panelPreguntasLayout);
        panelPreguntasLayout.setHorizontalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPreguntasLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPreguntasLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnPreguntas))
                    .addGroup(panelPreguntasLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(labelPreguntas)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelPreguntasLayout.setVerticalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(labelPreguntas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPreguntas)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preguntas", panelPreguntas);

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Juego", panelJuego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLoginActionPerformed
        switch (cmbLogin.getSelectedIndex()) {
            case 1:
                if (!txtNick.getText().trim().equalsIgnoreCase("") || !txtPass.getText().trim().equalsIgnoreCase("")) {
                    jugador = new Jugador(txtNick.getText(), txtPass.getText());
                    if (jugador.verificarRegistro(txtNick.getText())) {
                        jugador.registrarJugador();
                        JOptionPane.showMessageDialog(panelLogin, "Se ha registrado con exito");
                    } else {
                        JOptionPane.showMessageDialog(panelLogin, "Ya se encuentra registrado en el juego", "Ha ocurrido un problema", JOptionPane.ERROR_MESSAGE);
                    }
                    txtNick.setText("");
                    txtPass.setText("");
                } else {
                    JOptionPane.showMessageDialog(panelLogin, "No puede dejar los espacios en blanco", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    txtNick.setText("");
                     txtPass.setText("");
                }
                break;
            case 2:
                if (!txtNick.getText().trim().equalsIgnoreCase("") || !txtPass.getText().trim().equalsIgnoreCase("")) {
                    jugador = new Jugador();
                    if (jugador.verificarLogin(txtNick.getText(), txtPass.getText())) {
                        cmbOpciones.setVisible(true);
                        labelLogin.setVisible(true);
                        cmbOpciones.setEnabled(true);
                        labelLogin.setEnabled(true);
                        JOptionPane.showMessageDialog(panelLogin, "Ha iniciado sesión correctamente", "Felicidades", JOptionPane.INFORMATION_MESSAGE);
                        txtNick.setText("");
                        txtPass.setText("");
                    }                    
                }else{
                        JOptionPane.showMessageDialog(panelLogin, "No puede dejar los espacios en blanco", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        txtNick.setText("");
                        txtPass.setText("");
                    }
                break;
        }
    }//GEN-LAST:event_cmbLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Este juego consiste en responder una serie de preguntas acerca de cultura general "
                + "\n" + ", se le dara 30 segungos para responder a cada una de las preguntas."
                + "\n" + "El juego esta dividido en 3 secciones, la secciòn de login en la cual te tendras que registrar y en caso de que"
                + "\n" + "ya lo èstes, te tendra que logear, en la secciòn de preguntas, tù podras añadir preguntas al juego, las cuales seran parte del juego,"
                + "\n" + "y por ùltimo tenemos la secciòn del juego en la cual se llevara a cabo toda la experiencia :D", "Instrucciones", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionesActionPerformed
        switch (cmbOpciones.getSelectedIndex()) {
            case 1:
                jTabbedPane1.setEnabledAt(0, false);
                jTabbedPane1.setEnabledAt(1, true);
                jTabbedPane1.setSelectedComponent(panelPreguntas);
                labelPreguntas.setText("Escriba el enunciado de la pregunta");
                panelLogin.setLayout(null);
                labelPreguntas.setAlignmentY(panelLogin.getWidth()/2);
                break;
            case 2:
                jTabbedPane1.setEnabledAt(0, false);
                jTabbedPane1.setEnabledAt(2, true);
                jTabbedPane1.setSelectedComponent(panelJuego);
                break;
        }
    }//GEN-LAST:event_cmbOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Juego().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JComboBox<String> cmbLogin;
    private javax.swing.JComboBox<String> cmbOpciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPreguntas;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelPreguntas;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
